// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// get_nlines
long get_nlines(std::string fn);
RcppExport SEXP _Siccuracy_get_nlines(SEXP fnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fn(fnSEXP);
    rcpp_result_gen = Rcpp::wrap(get_nlines(fn));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Siccuracy_get_nlines", (DL_FUNC) &_Siccuracy_get_nlines, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_Siccuracy(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
