# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'
#' \code{get_nlines} returns number of lines. Last line, if empty, is ignored.
#' 
#' @param fn Filename.
#' @export
#' @return \code{get_nlines}: Number of lines, or \code{0} on error.
#' @rdname auxfunc
#' @aliases get_nlines
#' @name get_nlines
#' @include auxil.R
get_nlines <- function(fn) {
    .Call('_Siccuracy_get_nlines', PACKAGE = 'Siccuracy', fn)
}

